// Code generated by goctl. DO NOT EDIT.
// Source: base.proto

package server

import (
	"context"

	"base/rpc/base"
	"base/rpc/internal/logic"
	"base/rpc/internal/svc"
)

type BaseServiceServer struct {
	svcCtx *svc.ServiceContext
	base.UnimplementedBaseServiceServer
}

func NewBaseServiceServer(svcCtx *svc.ServiceContext) *BaseServiceServer {
	return &BaseServiceServer{
		svcCtx: svcCtx,
	}
}

func (s *BaseServiceServer) GetBalance(ctx context.Context, in *base.GetBalanceReq) (*base.GetBalanceResp, error) {
	l := logic.NewGetBalanceLogic(ctx, s.svcCtx)
	return l.GetBalance(in)
}

func (s *BaseServiceServer) Create(ctx context.Context, in *base.CreateReq) (*base.CreateResp, error) {
	l := logic.NewCreateLogic(ctx, s.svcCtx)
	return l.Create(in)
}
