// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	"base/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/base/wallet/balance",
				Handler: getBalanceHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/base/wallet/create",
				Handler: createHandler(serverCtx),
			},
		},
		rest.WithPrefix("/v1"),
	)
}
