// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.3

package handler

import (
	"net/http"

	"market-monitor/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/subscribeBinanceAccount",
				Handler: SubscribeBinanceAccountHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/subscribeTwitterAccount",
				Handler: SubscribeTwitterAccountHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/api/v1/monitor"),
	)
}
