// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.3

package types

type LoginSignRequest struct {
	Message   string `json:"message"` // 其中有 nonce 防止用户重复签名，nonce 由后端发放并且由后端验证
	Signature string `json:"signature"`
}

type UserInfoResponse struct {
	Id       int64  `json:"id"`
	Username string `json:"username"`
	Address  string `json:"address"`
	Email    string `json:"email"`
	Tier     string `json:"tier"`
}
