// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.3

package types

type LoginRequest struct {
	Username string `json:"username"`
	Password string `json:"password"`
}

type UserInfoResponse struct {
	Id       int64  `json:"id"`
	Username string `json:"username"`
	Address  string `json:"address"`
	Email    string `json:"email"`
	Tier     string `json:"tier"`
}
