// Code generated by goctl. DO NOT EDIT.
package types

type CreateResp struct {
	Address   string `json:"address"`
	SecretKey string `json:"secretKey"`
}

type GetBalanceReq struct {
	Address string `json:"address"`
}

type GetBalanceResp struct {
	Balance string `json:"balance"`
}
